version: "3.4"
services:
  scanner:
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.30.0
    environment:
      ERIGON_URL: "http://op-erigon.dappnode:8545"
    image: "scanner.op-otterscan.public.dappnode.eth:0.1.0"
